baseURL = 'http://example.org'
languageCode = 'no-nb'
title = 'D.IT-I/O - Linjeforeningen'
theme = 'console'

pluralizelisttitles = "false"

[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = true

  # Set the animation style -- https://animate.style/
  # To disable animations, please remove or comment animationStyle parameter
  animateStyle = "animated zoomIn fast"

  [[params.navlinks]]
  name = "arrangementer/"
  url = "arrangementer/"

  [[params.navlinks]]
  name = "om oss/"
  url = "om_oss/"

  [[params.navlinks]]
  name = "bilder/"
  url = "photos/"



# Sidebar: about/bio
[params.about]
title = "D.IT-I/O"
description = "Linjeforeningen for insitutt IT ved OsloMet"
# unicode/emoji logo:
# logo = "🍚"
# or use an image:
#logo_image = "images/rice.svg"

[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/Ditio-Linjeforening/"

[[params.socialLinks]]
icon = "fa-solid fa-envelope"
title = "Email"
url = "mailto:ditio.kontakt@gmail.com"


